version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Exclude node_modules to use container's version
      - /app/node_modules
      # Exclude .next to use container's build
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=${DATABASE_URL:-file:./dev.db}
      - PORT=3000
    stdin_open: true
    tty: true
