@session_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjIyNzc3NTh9.bObcSC8xYRa2fPGKc3cR2LESZHt-tBb1y862grDWc0Q

### Register
POST http://localhost:8080/user/register
Content-Type: application/json

{
    "fullname": "admin",
    "email": "admin@mail.com",
    "password": "admin123"
}

### Login
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin123"
}

### Logout
POST http://localhost:8080/user/logout

### Get Profile
GET http://localhost:8080/user/profile

### Get Profile with cookies
GET http://localhost:8080/user/profile
Cookie: session_token={{session_token}}

### Refresh token
POST http://localhost:8080/user/refresh

### Create Post
POST http://localhost:8080/posts

{
    "title": "I am a new post and published",
    "thumbnail": null,
    "description": "Quis voluptas dolore",
    "content": "<p>ssasasasjaoijsajisas</p>",
    "published": true,
    "publishedAt": null,
    "category": "BERITA"
}

### Get Posts
GET http://localhost:8080/posts?page=1&limit=10


### Upload Image
POST http://localhost:3000/api/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="coba.jpg"
Content-Type: image/jpeg

< /Users/ryotwell/Projects/smpuhamzanwadi/public/assets/images/coba.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--