import { PENDIDIKAN_OPTIONS, PENGHASILAN_OPTIONS } from '@/lib/model/student';
import { z } from 'zod'

export const biodataSchema = z.object({
    full_name: z.string().min(2, "Nama harus minimal 2 karakter").max(64, "Nama maksimal 64 karakter"),
    nisn: z.string().min(10, "NISN harus 10 digit angka").max(10, "NISN harus 10 digit angka").regex(/^\d{10}$/, "NISN harus 10 digit angka"),
    nik: z.string().min(16, "NIK harus 16 digit angka").max(16, "NIK harus 16 digit angka").regex(/^\d{16}$/, "NIK harus 16 digit angka"),
    asal_sekolah: z.string().min(2, "Asal sekolah minimal 2 karakter").max(64, "Asal sekolah maksimal 64 karakter"),
    tempat_lahir: z.string().min(2, "Tempat lahir minimal 2 karakter").max(64, "Tempat lahir maksimal 64 karakter"),
    tanggal_lahir: z.string().min(8, "Tanggal lahir diperlukan"),
    gender: z.enum(["MALE", "FEMALE"], "Pilih jenis kelamin"),
    agama: z.enum(["ISLAM", "CHRISTIAN", "CATHOLIC", "HINDU", "BUDDHA", "KONGHUCU"], "Pilih agama"),
    keadaan_ortu: z.enum(["LENGKAP", "YATIM", "PIATU", "YATIM_PIATU"], "Pilih keadaan orang tua"),
    status_keluarga: z.enum(["ANAK_KANDUNG", "ANAK_TIRI", "ANAK_ANGKAT"], "Pilih status keluarga"),
    anak_ke: z.number().int().positive("Anak ke harus bilangan positif"),
    dari_bersaudara: z.number().int().positive("Dari bersaudara harus bilangan positif"),
    tinggal_bersama: z.enum(["ORANG_TUA", "KAKEK_NENEK", "PAMAN_BIBI", "SAUDARA_KANDUNG", "KERABAT", "PANTI_PONTREN", "LAINNYA"], "Pilih tinggal bersama"),
    tinggal_bersama_lainnya: z.string().optional(),
    kewarganegaraan: z.enum(["WNI", "WNA"], "Pilih kewarganegaraan"),
    rt: z.string().optional(),
    rw: z.string().optional(),
    desa_kelurahan: z.string().min(2, "Desa/Kelurahan minimal 2 karakter"),
    kecamatan: z.string().min(2, "Kecamatan minimal 2 karakter"),
    kabupaten: z.string().min(2, "Kabupaten minimal 2 karakter"),
    provinsi: z.string().min(2, "Provinsi minimal 2 karakter"),
    kode_pos: z.string().min(5, "Kode pos harus 5 digit").max(5, "Kode pos harus 5 digit"),
    alamat_jalan: z.string().optional(),
    phone: z.string().min(8, "Nomor HP minimal 8 digit").max(18, "Nomor HP tidak boleh lebih dari 18 karakter").regex(/^08\d{7,16}$/, "Nomor HP harus dimulai dari 08 dan angka"),
    email: z.string().email("Email tidak valid").optional().or(z.literal("")),
    blood_type: z.enum(["A", "B", "AB", "O", "UNKNOWN"], "Pilih golongan darah"),
    berat_kg: z.number().int("Berat badan harus bilangan bulat").optional(),
    tinggi_cm: z.number().int("Tinggi badan harus bilangan bulat").optional(),
    riwayat_penyakit: z.string().optional(),

    // Orang Tua dan Wali
    father_name: z.string().min(2, "Nama ayah wajib diisi"),
    father_education: z.enum(PENDIDIKAN_OPTIONS.map((item) => item.value) as [string, ...string[]], "Pendidikan ayah wajib dipilih"),
    father_job: z.string().min(1, "Pekerjaan ayah wajib diisi"),
    father_income: z.enum(PENGHASILAN_OPTIONS.map((item) => item.value) as [string, ...string[]], "Penghasilan ayah wajib dipilih"),
    mother_name: z.string().min(2, "Nama ibu wajib diisi"),
    mother_education: z.enum(PENDIDIKAN_OPTIONS.map((item) => item.value) as [string, ...string[]], "Pendidikan ibu wajib dipilih"),
    mother_job: z.string().min(1, "Pekerjaan ibu wajib diisi"),
    mother_income: z.enum(PENGHASILAN_OPTIONS.map((item) => item.value) as [string, ...string[]], "Penghasilan ibu wajib dipilih"),

    wali_name: z.string().min(2, "Nama wali wajib diisi"),
    no_hp_ortu_wali: z.string().min(8, "Nomor HP wali minimal 8 digit").max(18, "Nomor HP wali tidak boleh lebih dari 18 karakter").regex(/^08\d{7,16}$/, "Nomor HP wali harus dimulai dari 08 dan angka"),
    parent_email: z.string().email("Email wali tidak valid"),
    alamat_ortu_wali: z.string().min(2, "Alamat wali wajib diisi"),
});